### ISSUE TITLE
Screenshots.py > no attribute 'screenshot_all_screenshots'

### ISSUE THREAD

**Issue by tk21** [MCGallaspy/ka-lite#6]
Exception occurred:
  File "screenshot.py", line 34, in process_screenshots
    all_args = map(lambda x: x['from_str_arg'], env.screenshot_all_screenshots)
AttributeError: BuildEnvironment instance has no attribute 'screenshot_all_screenshots'

**Comment by MCGallaspy** [comment]
Fixed now in `sphinx-docs`.
